# Generated by Django 2.1 on 2019-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Автор')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('biography', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Биография автора')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_images', verbose_name='Автор')),
            ],
        ),
    ]
